on:
  push:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
name: Sync
jobs:
  sync:
    secrets: inherit
    uses: r-universe-org/workflows/.github/workflows/sync.yml@v3
    with:
      token: ${{ secrets.PAT_FOR_UNIVERSE }}
